print("Welcome To My Bot\n")
name= input("What is your name?\n")
print(name + " " "can you believe that your name sounds great and beautiful" + " " "!\n")
input ("Would you love me to give you some compositions about yourself, Yes or No?\n")
gender= input("Are you a boy or girl?\n")
print(len(gender))
print(name + " " "Is one of the most beautiful" + " " + gender + "" + "\n" + "" + name + " " "Is very beautiful and jovial\n" + "" + name + " " + "loves to eat and kind to people\n")
input("How much would you love to rate us, 50, 100 ?\n")
print("Thank You😀😀, We would love to see you another day!")
